export const HOME = '/';
export const PRODUCT_DETAILS = '/product/:id';
export const SEARCH_BY_KEYWORD = '/search/:keyword';
export const FORGOT_PASSWORD = '/password/forgot';
export const RESET_PASSWORD = '/password/reset/:token';
export const LOGIN = '/login';
export const REGISTER = '/register';
export const CART = '/cart';
export const MY_ORDERS = '/orders/me';
export const MY_PROFILE= '/me';
export const UPDATE_PROFILE = '/me/update';
export const UPDATE_PASSWORD = '/password/update';
export const DASHBOARD = '/dashboard';
export const CONFIRM_ORDER_PAGE = '/order/confirm';
export const ORDER_SUCCESS = '/order/success';
export const VIEW_ORDER = '/view-order/:orderId';
export const SHIPPING_PAGE = '/shipping';
export const PAYMENT = '/payment';

export const VIEW_ALL_PRODUCTS = '/admin/products';
export const CREATE_PRODUCT = '/admin/product';
export const VIEW_ALL_ORDERS = '/admin/orders';
export const VIEW_ALL_USERS = '/admin/users';
export const VIEW_ALL_REVIEWS = '/admin/reviews';
export const UPDATE_ORDER_STATUS = '/admin/order/:id'
export const UPDATE_PRODUCT = '/admin/product/:id';
export const UPDATE_USER = '/admin/user/:id';